version: '3.3'
services:
  #Web app, we build the Dockerfile directly from here.
  war-test:
    build: .
    ports:
      - "8080:8080"
  #MySQL DB
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: AncyDB
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ancy
      # You can use whatever password you like
      MYSQL_PASSWORD: Ancy@194237
      # Password for root access
      MYSQL_ROOT_PASSWORD: Ancy@194237
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: